# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\"0\n\x0eUsuarioRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x02 \x01(\t\"=\n\x0fUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x03 \x01(\t\"\x14\n\x12SuscripcionRequest2\xa5\x01\n\x0eUsuarioService\x12\x43\n\x0c\x43rearUsuario\x12\x18.usuarios.UsuarioRequest\x1a\x19.usuarios.UsuarioResponse\x12N\n\x11SuscribirUsuarios\x12\x1c.usuarios.SuscripcionRequest\x1a\x19.usuarios.UsuarioResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIOREQUEST']._serialized_start=28
  _globals['_USUARIOREQUEST']._serialized_end=76
  _globals['_USUARIORESPONSE']._serialized_start=78
  _globals['_USUARIORESPONSE']._serialized_end=139
  _globals['_SUSCRIPCIONREQUEST']._serialized_start=141
  _globals['_SUSCRIPCIONREQUEST']._serialized_end=161
  _globals['_USUARIOSERVICE']._serialized_start=164
  _globals['_USUARIOSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
