# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pedidos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pedidos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpedidos.proto\x12\x07pedidos\"D\n\rPedidoRequest\x12\x0f\n\x07\x63liente\x18\x01 \x01(\t\x12\x10\n\x08producto\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\"a\n\x0ePedidoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\x10\n\x08producto\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\"\x14\n\x12SuscripcionRequest2\x9b\x01\n\rPedidoService\x12>\n\x0b\x43rearPedido\x12\x16.pedidos.PedidoRequest\x1a\x17.pedidos.PedidoResponse\x12J\n\x10SuscribirPedidos\x12\x1b.pedidos.SuscripcionRequest\x1a\x17.pedidos.PedidoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedidos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOREQUEST']._serialized_start=26
  _globals['_PEDIDOREQUEST']._serialized_end=94
  _globals['_PEDIDORESPONSE']._serialized_start=96
  _globals['_PEDIDORESPONSE']._serialized_end=193
  _globals['_SUSCRIPCIONREQUEST']._serialized_start=195
  _globals['_SUSCRIPCIONREQUEST']._serialized_end=215
  _globals['_PEDIDOSERVICE']._serialized_start=218
  _globals['_PEDIDOSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
