# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pedidos_pb2 as pedidos__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pedidos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PedidoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearPedido = channel.unary_unary(
                '/pedidos.PedidoService/CrearPedido',
                request_serializer=pedidos__pb2.PedidoRequest.SerializeToString,
                response_deserializer=pedidos__pb2.PedidoResponse.FromString,
                _registered_method=True)
        self.SuscribirPedidos = channel.unary_stream(
                '/pedidos.PedidoService/SuscribirPedidos',
                request_serializer=pedidos__pb2.SuscripcionRequest.SerializeToString,
                response_deserializer=pedidos__pb2.PedidoResponse.FromString,
                _registered_method=True)


class PedidoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CrearPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuscribirPedidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PedidoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearPedido,
                    request_deserializer=pedidos__pb2.PedidoRequest.FromString,
                    response_serializer=pedidos__pb2.PedidoResponse.SerializeToString,
            ),
            'SuscribirPedidos': grpc.unary_stream_rpc_method_handler(
                    servicer.SuscribirPedidos,
                    request_deserializer=pedidos__pb2.SuscripcionRequest.FromString,
                    response_serializer=pedidos__pb2.PedidoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedidos.PedidoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pedidos.PedidoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PedidoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pedidos.PedidoService/CrearPedido',
            pedidos__pb2.PedidoRequest.SerializeToString,
            pedidos__pb2.PedidoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuscribirPedidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pedidos.PedidoService/SuscribirPedidos',
            pedidos__pb2.SuscripcionRequest.SerializeToString,
            pedidos__pb2.PedidoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
